# Dezvoltare software analiza date
## Seminar 3

In [2]:
import pandas as pd
import numpy as np

In [23]:
coduri_judete_df = pd.read_csv('./data_in/Coduri_Judete.csv')
coduri_regiuni_df = pd.read_csv('./data_in/Coduri_Regiuni.csv')
industria_alimentara_df = pd.read_csv('./data_in/IndustriaAlimentara.csv',index_col=0)
populatia_localitatii_df = pd.read_csv('./data_in/PopulatieLocalitati.csv')

În fișierul *IndustriaAlimentara.csv* se află informații privind numărul de angajați în industria alimentară la nivel de localitate. Informațiile sunt următoarele:

- *Siruta* - Codul Siruta al localității; https://www.siruta.nxm.ro
- *Localitate* - Denumirea localității;
- *Carne*, *Peste*, *LegumeFructe*, *Uleiuri*, *Lactate*, *Morarit*, *Panificatie* - Valorile reprezentând numărul de angajați pe principalele activități din industria alimentară.

În fișierul *PopulatieLocalitati.csv* se află populația pe localități și indicativele de județ pentru fiecare localitate.

 În fișierele *Coduri_Judete.csv* și *Coduri_Regiuni.csv* sunt codificări la nivel de județe și regiuni.

## Explorare dataset

In [7]:
print("Coduri judete:")
display(coduri_judete_df.head())

print("Coduri regiuni:")
display(coduri_regiuni_df.head())

print("Industria alimentara:")
display(industria_alimentara_df.head())

print("Populatia localitati:")
display(populatia_localitatii_df.head())

Coduri judete:

  IndicativJudet             NumeJudet          Regiune
0             ab                  Alba           Centru
1             ag                 Arges              Sud
2             ar                  Arad             Vest
3              b  Municipiul Bucuresti  Bucuresti-Ilfov
4             bc                 Bacau         Nord-Est

Coduri regiuni:

     Regiune  MacroRegiune
0     Centru             1
1  Nord-Vest             1
2       Vest             4
3   Sud-Vest             4
4        Sud             3

Industria alimentara:

,Siruta,Localitate,Carne,Peste,LegumeFructe,Uleiuri,Lactate,Morarit,Panificatie
0,32768,Budesti,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,49153,Sahateni,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,57350,Cojocna,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,90119,Lunca Cernii De Jos,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,73736,Poiana Mare,0.0,0.0,2.0,0.0,0.0,0.0,0.0

Populatia localitati:

   Siruta             Localitate Judet  Populatie
0    1017  Municipiul Alba Iulia    ab      74283
1    1071                 Ciugud    ab       2983
2    1151             Oras Abrud    ab       5513
3    1213        Municipiul Aiud    ab      26318
4    1348        Municipiul Blaj    ab      20994

## Încălzire

1. Calculați totalul vânzărilor pe fiecare produs și pe fiecare magazin. Afișați doar magazinele care au vândut ceva.
2. Pentru fiecare magazin, găsiți produsul cel mai vândut. Ce diferă între `max`, `argmax` și `idxmax`?
3. Aduceți populația orașului lângă fiecare magazin, apoi calculați vânzările totale pe oraș raportate la populație.
4. ★ Calculați, pentru fiecare magazin, ponderea vânzărilor sale în totalul vânzărilor din orașul în care se află.

   $$Pondere_{m} = \frac{TotalVanzari_{m}}{TotalVanzari_{oras(m)}}$$

   Verificare: suma ponderilor magazinelor din același oraș trebuie să fie 1.

In [8]:
vanzari = pd.DataFrame({
    "Magazin": ["M1", "M2", "M3", "M4", "M5"],
    "Oras":    ["Buc", "Buc", "Cluj", "Iasi", "Cluj"],
    "Paine":   [10, 0, 5, 8, 2],
    "Lapte":   [4, 0, 7, 2, 1],
    "Carne":   [6, 0, 3, 0, 9],
}).set_index("Magazin")

orase = pd.DataFrame({
    "Oras": ["Buc", "Cluj", "Iasi"],
    "Populatie": [2000, 400, 300],
}).set_index("Oras")

produse = ["Paine", "Lapte", "Carne"]

## Cerinte

1. Să se salveze în fișierul *Cerinta1.csv* datele privind numărul de angajați pe activitățile din industria alimentară, pentru localitățile în care numărul total de angajați este mai mare decât 0. Fișierul *Cerinta1.csv* va avea aceleași coloane ca fișierul *IndustriaAlimentara.csv*.

*hint:* `apply` sau `sum(!atentie la parametrul axis)`

In [18]:
# industria_alimentara_df.head()
greater_than_0 = industria_alimentara_df[industria_alimentara_df.columns[1:]].sum(axis=1)>0
industria_alimentara_df[greater_than_0]
industria_alimentara_df[industria_alimentara_df["Uleiuri"]>0]
industria_alimentara_df["Uleiuri"]

Siruta
32768     0.0
49153     0.0
57350     0.0
90119     0.0
73736     0.0
         ...
122864    0.0
163832    0.0
40955     0.0
131069    0.0
98300     7.0
Name: Uleiuri, Length: 3181, dtype: float64

In [ ]:
%%sql

2. Să se calculeze și să se salveze în fișierul *Cerinta2.csv* procentul de angajați pe fiecare activitate la nivel de localitate.

In [24]:
industria_alimentara_df[greater_than_0]
# CA SA FAC PE LINII FOLOSESC APPLY!!!
def functie_parcurgere(linie):
    print(linie)
    print("--------")
    return linie/linie.sum()
industria_alimentara_df[industria_alimentara_df.columns[1:]].apply(functie_parcurgere, axis=1)

Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 32768, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 49153, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         1.0
Morarit         0.0
Panificatie     0.0
Name: 57350, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 90119, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    2.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 73736, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     9.0
Name: 147465, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 155662, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 139287, dtype: float64
--------
Carne            12.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           3.0
Morarit           0.0
Panificatie     307.0
Name: 114710, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     44.0
Name: 122908, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     44.0
Name: 131103, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 40991, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 98337, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 8229, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 16427, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 32811, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 73772, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     59.0
Name: 172082, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     1.0
Name: 49206, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 24631, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 163903, dtype: float64
--------
Carne            47.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate          10.0
Morarit           0.0
Panificatie     110.0
Name: 106559, dtype: float64
--------
Carne           3.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     7.0
Name: 139330, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 81987, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     74.0
Name: 98373, dtype: float64
--------
Carne             0.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           0.0
Morarit           4.0
Panificatie     105.0
Name: 147526, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         2.0
Panificatie     0.0
Name: 16454, dtype: float64
--------
Carne            2.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     26.0
Name: 65609, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 122953, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     15.0
Name: 41033, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 155724, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 49233, dtype: float64
--------
Carne             0.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           0.0
Morarit           0.0
Panificatie     275.0
Name: 16472, dtype: float64
--------
Carne           2831.0
Peste              0.0
LegumeFructe       0.0
Uleiuri            0.0
Lactate            0.0
Morarit            0.0
Panificatie        1.0
Name: 139358, dtype: float64
--------
Carne           10.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie      0.0
Name: 90208, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 57449, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 65645, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         19.0
Panificatie     16.0
Name: 155760, dtype: float64
--------
Carne           292.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           0.0
Morarit           0.0
Panificatie       0.0
Name: 32884, dtype: float64
--------
Carne           218.0
Peste             0.0
LegumeFructe      1.0
Uleiuri           0.0
Lactate           0.0
Morarit           0.0
Panificatie     263.0
Name: 114809, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     4.0
Name: 16506, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 172153, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     17.0
Name: 73852, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     27.0
Name: 106620, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 163967, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 82047, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 147580, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         13.0
Panificatie      3.0
Name: 41088, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 139394, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     2.0
Name: 98435, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 123013, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 24711, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     21.0
Name: 131210, dtype: float64
--------
Carne             0.0
Peste             0.0
LegumeFructe      4.0
Uleiuri           0.0
Lactate           0.0
Morarit           0.0
Panificatie     121.0
Name: 65681, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 90262, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         11.0
Panificatie      0.0
Name: 155797, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    1.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 41113, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 106648, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 49313, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 8354, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     17.0
Name: 16551, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     1.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     31.0
Name: 114854, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 65707, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 73905, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 147633, dtype: float64
--------
Carne           247.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           0.0
Morarit          21.0
Panificatie     216.0
Name: 131256, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 32955, dtype: float64
--------
Carne           896.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           0.0
Morarit           0.0
Panificatie     185.0
Name: 106684, dtype: float64
--------
Carne           2.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 24766, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         10.0
Panificatie      3.0
Name: 73923, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     1.0
Name: 155840, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         15.0
Panificatie      0.0
Name: 98505, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 131274, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     2.0
Name: 57546, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate         44.0
Morarit          0.0
Panificatie     12.0
Name: 147660, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     11.0
Name: 41177, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 65752, dtype: float64
--------
Carne           2.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 82136, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 164062, dtype: float64
--------
Carne           2.0
Peste           0.0
LegumeFructe    2.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 123102, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 16613, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 90342, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     11.0
Name: 8425, dtype: float64
--------
Carne            2.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     68.0
Name: 114925, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate         16.0
Morarit          0.0
Panificatie      1.0
Name: 57582, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 172279, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 33015, dtype: float64
--------
Carne           155.0
Peste             0.0
LegumeFructe      0.0
Uleiuri           0.0
Lactate           3.0
Morarit           0.0
Panificatie      53.0
Name: 106746, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 147713, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 24837, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     2.0
Name: 155911, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     86.0
Name: 131336, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     3.0
Name: 73996, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 16659, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 114970, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         10.0
Panificatie      0.0
Name: 49439, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     32.0
Name: 106782, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 41248, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 123175, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     5.0
Name: 164133, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 98603, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 57644, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 74028, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          1.0
Morarit          3.0
Panificatie     29.0
Name: 65841, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit         85.0
Panificatie      5.0
Name: 172340, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 155957, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         0.0
Panificatie     0.0
Name: 90431, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     2.0
Uleiuri          0.0
Lactate          2.0
Morarit          0.0
Panificatie     58.0
Name: 106817, dtype: float64
--------
Carne            0.0
Peste            0.0
LegumeFructe     0.0
Uleiuri          0.0
Lactate          0.0
Morarit          0.0
Panificatie     13.0
Name: 82243, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         2.0
Morarit         0.0
Panificatie     0.0
Name: 41284, dtype: float64
--------
Carne           0.0
Peste           0.0
LegumeFructe    0.0
Uleiuri         0.0
Lactate         0.0
Morarit         9.0

           Carne  Peste  LegumeFructe  Uleiuri  Lactate  Morarit  Panificatie
Siruta
32768        NaN    NaN           NaN      NaN      NaN      NaN          NaN
49153        NaN    NaN           NaN      NaN      NaN      NaN          NaN
57350   0.000000    0.0           0.0      0.0      1.0      0.0     0.000000
90119        NaN    NaN           NaN      NaN      NaN      NaN          NaN
73736   0.000000    0.0           1.0      0.0      0.0      0.0     0.000000
...          ...    ...           ...      ...      ...      ...          ...
122864  0.000000    0.0           0.0      0.0      0.0      0.0     1.000000
163832       NaN    NaN           NaN      NaN      NaN      NaN          NaN
40955   0.898876    0.0           0.0      0.0      0.0      0.0     0.101124
131069  0.000000    0.0           0.0      0.0      0.0      0.3     0.700000
98300   0.000000    0.0           0.0      1.0      0.0      0.0     0.000000

[3181 rows x 7 columns]

3. Să se salveze în fișierul *Cerinta3.csv* județele sortate descrescător după ponderea angajaților din industria alimentară în populația totală.

In [36]:
industria_alimentara_df.join(populatia_localitatii_df, rsuffix="RIGHT_",lsuffix="_LEFT")
# suffix tabele ca la SQL

industria_alimentara_df.groupby("Judet").aggregate("sum").head()
# agregare_judete.columns
# columns = ["Carne","Peste"]

MergeError: Passing 'suffixes' which cause duplicate columns {'LocalitateRIGHT_', 'Localitate_LEFT'} is not allowed.

4. Să se salveze în fișierul *Cerinta4.csv* activitatea cu cei mai mulți angajați la nivel de județ. Se va afișa indicativul de județ și activitatea dominantă.

*hint*: `max` vs `argmax`

5. Să se calculeze, pentru fiecare regiune, numărul mediu de angajați pe fiecare activitate din industria alimentară și să se salveze rezultatul în fișierul *Cerinta5.csv*. Media se calculează ca medie ponderată la nivel de localitate, ponderea fiecărei localități fiind populația sa.

   $$\bar{x}_{r,j} = \frac{\sum_{k \in r} x_{k,j} \cdot P_k}{\sum_{k \in r} P_k}$$

   unde $x_{k,j}$ este numărul de angajați din activitatea $j$ în localitatea $k$, iar $P_k$ este populația localității $k$.


*HINT*: Atentie la join-uri(mai ales la index)

6. Să se calculeze, pentru fiecare județ și fiecare activitate, indicele de localizare și să se salveze rezultatul în fișierul *Cerinta6.csv*.

   Indicele de localizare arată cât de concentrată este o activitate într-un județ, raportat la mărimea județului. Se calculează ca raport între:
   * ponderea județului *i* în numărul total de angajați din activitatea *j* la nivel național, și
   * ponderea județului *i* în populația totală a țării.

   $$IL_{i,j} = \frac{A_{i,j} / A_j}{P_i / P}$$

   unde $A_{i,j}$ este numărul de angajați din activitatea $j$ în județul $i$, $A_j$ este numărul total de angajați din activitatea $j$ la nivel național, $P_i$ este populația județului $i$, iar $P$ este populația totală.

   O valoare $IL > 1$ înseamnă că activitatea este mai concentrată în județ decât ar justifica populația acestuia.

   **Exemplu:** județul *x* are 3.000 de angajați în industria cărnii și 200.000 de locuitori. La nivel național sunt 100.000 de angajați în industria cărnii și 20.000.000 de locuitori.

   $$IL_{x,\text{Carne}} = \frac{3\,000 / 100\,000}{200\,000 / 20\,000\,000} = \frac{0{,}03}{0{,}01} = 3$$

   Așadar, județul *x* are de 3 ori mai mulți angajați în industria cărnii decât ar fi de așteptat după populația sa.

7. Pe baza rezultatelor din *Cerinta6.csv*, să se identifice județele cu cea mai puternică specializare într-o activitate. Pentru fiecare județ se determină indicele de localizare maxim (pe toate activitățile) și activitatea corespunzătoare. Județele se sortează descrescător după acest indice și rezultatul se salvează în fișierul *Cerinta7.csv*.

   $$IL^{max}_i = \max_j IL_{i,j}$$

   Județele din capul listei sunt *outlieri*: au o activitate mult mai concentrată decât ar justifica populația lor.

   *hint:* `max(axis=1)`, `idxmax(axis=1)`, `sort_values`